### PR TITLE
Add support for the ConnectCore 8X SBC Pro

### PR DESCRIPTION
**Pull request by alexgg**

### CODE REVIEW

**Comment by nazrhom** [comment]
@balena-ci test

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@balena-ci retest

**Comment by alexgg** [comment]
@balena-ci retest

**Comment by alexgg** [comment]
@balena-ci retest

**Comment by alexgg** [comment]
@balena-ci retest

**Comment by alexgg** [comment]
@balena-ci retest

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@balena-ci test

**Comment by alexgg** [comment]
@resin-jenkins test this please

**Comment by alexgg** [comment]
@resin-jenkins test this please

**Comment by alexgg** [comment]
@balena-ci retest

**Comment by alexgg** [comment]
test this please

**Comment by alexgg** [comment]
@resin-jenkins test this please

**Comment by alexgg** [comment]
@balena-ci retest

**Comment by nazrhom** [comment]
@resin-jenkins retest this please

**Comment by nazrhom** [comment]
@resin-jenkins test this please

**Comment by alexgg** [comment]
@balena-ci retest

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Pull request merged**
