### PR TITLE
balena.yml: Add name

### PR DESCRIPTION
**Pull request by alexgg**
Use the hostapp name in the balena contract too.

Change-type: patch
Signed-off-by: Alex Gonzalez <alexg@balena.io>

### CODE REVIEW

**Comment by alexgg** [comment]
@balena-ci retest

**Comment by alexgg** [comment]
@balena-ci rebase

**Comment by alexgg** [comment]
@balena-ci rebase

**Comment by alexgg** [comment]
@balena-ci retest

**Comment by alexgg** [comment]
@balena-ci rebase

**Comment by alexgg** [comment]
@balena-ci rebase

**Comment by alexgg** [comment]
@balena-ci rebase

**Comment by alexgg** [comment]
@balena-ci rebase

**Comment by alexgg** [comment]
@balena-ci rebase

**Comment by alexgg** [comment]
@balena-ci rebase

**Comment by alexgg** [comment]
@balena-ci I self-certify!

**Comment by acostach** [comment]
@alexgg how should this file look like for device repos that have multiple boards? Should it have multiple name entries?

```
name: device-slug1
name: device-slug2
...
type: sw.application
version: 2.85.14 
```

**Comment by alexgg** [comment]
> how should this file look like for device repos that have multiple boards? Should it have multiple name entries?

hi @acostach I wasn't planning to add it, this was just meant to be a test commit to test the versioning. I will revert the change as well as the `repo.yml` and local `versionist.conf.js` once the versioning changes are live not to confuse things.

As part of the balenaOS contract improvement discussions we have been speaking about having an OS contract and a device contract and merge them, and ideally in that process we would dynamically add the board specific details. But that is no more than a general high level concept, nothing has been done in that regards.

**Comment by acostach** [comment]
Understood, thank you for clarifying Alex

**Pull request merged**
